image: thyrlian/android-sdk

stages:
  - build
  - test

build_release:
  script:
    - apt-get --quiet update --yes
    - apt install curl
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt install nodejs
    - export GRADLE_USER_HOME=$(pwd)/android/.gradle
    - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    - chmod +x ./android/gradlew
    - apt-get --quiet install --yes npm default-jdk default-jre git
    - $ANDROID_HOME/tools/bin/sdkmanager "lldb;3.1" > /dev/null
    - $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.4111459" > /dev/null
    - $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle" > /dev/null
    - ls $ANDROID_HOME
    - ls $ANDROID_NDK_HOME
    - npm install -g react-native-cli
    - npm install
    - npm run build-android-release
  stage: build
  artifacts:
    paths:
      - android/app/build/outputs/apk/release

e2e_tests:
  script:
    - . ./tools/ci-setup-android-sdk.sh
    - npm run test-e2e-android
  stage: test
