image: thyrlian/android-sdk
# image: jangrewe/gitlab-ci-android
# image: ubuntu:18.04

stages:
  - build
  - test

before_script:
  - apt-get --quiet update --yes
  - export GRADLE_USER_HOME=$(pwd)/android/.gradle
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  - chmod +x ./android/gradlew

build_release:
  script:
    - apt-get --quiet install --yes npm default-jdk default-jre git
    # - . ./tools/ci-setup-android-sdk.sh
    - $ANDROID_HOME/tools/bin/sdkmanager "lldb;3.1" > /dev/null
    - $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.4111459" > /dev/null
    - $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle" > /dev/null
    - ls $ANDROID_HOME
    - ls $ANDROID_NDK_HOME
    - npm install -g react-native-cli
    - npm install
    - npm run build-android-release
  stage: build
  artifacts:
    paths:
      - android/build/outputs/

e2e_tests:
  script:
    - . ./tools/ci-setup-android-sdk.sh
    - npm run test-e2e-android
  stage: test
